"""
Add root passenger id

Revision ID: f73db89aeb00
Revises: d9f8de69e65d
Create Date: 2023-05-18 11:22:22.127813

"""
import sqlalchemy as sa
from alembic import op

revision = "f73db89aeb00"
down_revision = "d9f8de69e65d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("command_tracking", sa.Column("root_passenger_id", sa.String(length=255), nullable=True))
    op.add_column("event_tracking", sa.Column("root_passenger_id", sa.String(length=255), nullable=True))
    op.add_column("query_tracking", sa.Column("root_passenger_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query_tracking", "root_passenger_id")
    op.drop_column("event_tracking", "root_passenger_id")
    op.drop_column("command_tracking", "root_passenger_id")
    # ### end Alembic commands ###
