"""
Add initial tables

Revision ID: d9f8de69e65d
Revises:
Create Date: 2023-02-16 23:29:37.633378

"""
import sqlalchemy as sa
from alembic import op

revision = "d9f8de69e65d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_tracking",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("executor_name", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("execution_start", sa.DateTime(), nullable=False),
        sa.Column("execution_end", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_tracking",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("executor_name", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("execution_start", sa.DateTime(), nullable=False),
        sa.Column("execution_end", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query_tracking",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("executor_name", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("execution_start", sa.DateTime(), nullable=False),
        sa.Column("execution_end", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_tracking")
    op.drop_table("event_tracking")
    op.drop_table("command_tracking")
    # ### end Alembic commands ###
