version: '3'

services:
  bus-station-tracking:
    build:
      context: .
    image: bus-station-tracking:latest
    command: tail -f > /dev/null
    depends_on:
      - bus-station-tracking-postgres
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8501:8501

  bus-station-tracking-postgres:
    image: postgres:14.1
    volumes:
      - 'bus_station_tracking_postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: bus-station-tracking
    ports:
      - 5432:5432

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

volumes:
  bus_station_tracking_postgres_data:
