apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bus-station-tracking-postgres
  name: bus-station-tracking-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: bus-station-tracking-postgres
status:
  loadBalancer: {}
