apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bus-station-tracking-neo4j
  name: bus-station-tracking-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bus-station-tracking-neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bus-station-tracking-neo4j
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: bus-station-tracking-configmap
        image: neo4j:5.8.0
        imagePullPolicy: ""
        name: bus-station-tracking-neo4j
        ports:
        - containerPort: 7687
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: bus-station-tracking-neo4j-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: bus-station-tracking-neo4j-data
        persistentVolumeClaim:
          claimName: bus-station-tracking-neo4j-data
status: {}
